### ISSUE TITLE
Personas e Perfis de usuário

### ISSUE THREAD

**Issue by CarlosZoft** [Interacao-Humano-Computador/2021.2-PMBA#42]
Na documentação das Personas e dos perfis de usuário, faltaram explicações claras de como foram criadas e
seu processo de trabalho. Expliquem de onde foram tiradas a base para a criação dos perfis de usuário, ex: Caso
tenha sido originado do questionário, onde foi aplicado, por quem e para quem, em quais redes sociais, qual a
conclusão do questionário dentre outros.

**Comment by CarlosZoft** [comment]
Pessoas ausentes no Histórico de versão : @CarlosZoft @hericklima22 @isadoragalvaoss, basta dar assign e abrir um novo PR.

**Comment by jackesfonseca** [comment]
Realização das alterações solicitadas
